### PR TITLE
Add xylar as maintainer

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin/core, would someone be willing to merge this to add me as a maintainer of this feedstock?

**Comment by xylar** [comment]
@conda-forge/core, would someone be willing to merge this to add me as a maintainer of this feedstock?

**Comment by synapticarbors** [comment]
@xylar -- I've been trying to add myself to a bunch of pmlandwehr's feedstocks since they seem largely abandoned. Let me know if you find others that you need help with.

**Comment by xylar** [comment]
Thanks a lot!  I'll let you know if I come across other abandoned feedstocks but I'm not aware of others created by pmlandwehr so far.

**Pull request merged**
